#+title: RelazioneBasi
#+author: Cristian Tomass, Roland Gjopalaj, Giovanni Pantarotto

* Relazione Progetto Basi di Dati
** Indice
- [[Consegna]]
- [[Glossario Termini]]
** [[Documento di Specifiche]]
** [[Strutturazione dei requisiti]]
** [[Operazioni richieste]]
*** [[Operazione 1]]
*** [[Operazione 2]]
** [[Modello ER]]
** [[Regole di Gestione]]
*** [[Vincoli d'integrità]]
*** [[Regole di derivazione]]
** [[Progettazione Logica]]
*** [[Tabella volumi]]
*** [[Analisti ridondanze]]
*** [[Costi operazione]]
**** [[Presenza di ridondanza]]
**** [[Assenza di ridondanza]]
*** [[Eliminazione delle generalizzazioni]]
*** [[Selezione degli identificatori primari]]
*** [[Traduzione modello logico]]
** [[Progettazione Fisica]]
*** [[Definizione database in SQL]]
**** [[Definizione dati]]
***** [[Creazione tabelle]]
***** [[Definizione trigger]]
**** [[Popolazione database]]
**** [[Query]]
** [[Analisi con R]]
** [[Conclusioni]]

** Consegna
Si progetti uno schema entità/relazioni per la gestione di un registro automobilistico, facente parte del sistema informativo di un ufficio di motorizzazione, contenente le seguenti informazioni:
+ di ciascun veicolo interessa registrare la targa, la cilindrata, i cavalli fiscali, la velocità, il numero di posti e la data di immatricolazione;
+ i veicoli sono classificati in categorie (automobili, ciclomotori, camion, rimorchi, ecc.);
+ ciascun veicolo appartiene ad uno specifico modello;
+ tra i dati relativi ai veicoli, vi è la codifica del tipo di combustibile utilizzato;
+ di ciascun modello di veicolo è registrata la fabbrica di produzione e il numero delle versioni prodotte;
+ ciascun veicolo può avere uno o più proprietari, che si succedono nel corso della “vita” del veicolo; di ciascun proprietario interessa registrare cognome, nome e indirizzo di residenza.

Lo schema entità/relazioni dovrà essere completato con attributi "ragionevoli" per ciascuna entità, identificando le possibili chiavi e le relazioni necessarie per la gestione del sistema in esame.

A partire dallo schema entità/relazioni, si costruisca il corrispondente schema relazionale.

** Glossario Termini
| Registro Automoilistico | Veicolo                    |
|-------------------------+----------------------------|
| Dominio                 | informazione da registrare |
|                         | nel registro               |
|                         |                            |

** Documento di Specifiche
Si progetti uno schema entità/relazioni per la gestione di un registro automobilistico, facente parte del sistema informativo di un ufficio di motorizzazione, contenente le seguenti informazioni:
+ di ciascun veicolo interessa registrare la targa, la cilindrata, i cavalli fiscali, la velocità, il numero di posti e la data di immatricolazione;
+ i veicoli sono classificati in categorie (automobili, ciclomotori, camion, rimorchi, ecc.);
+ ciascun veicolo appartiene ad uno specifico modello;
+ tra i dati relativi ai veicoli, vi è la codifica del tipo di combustibile utilizzato;
+ di ciascun modello di veicolo è registrata la fabbrica di produzione e il numero delle versioni prodotte;
+ ciascun veicolo può avere uno o più proprietari, che si succedono nel corso della “vita” del veicolo; di ciascun proprietario interessa registrare cognome, nome e indirizzo di residenza.
  ./img/SchemaER.drawio(1).png
** Strutturazione dei requisiti
** Operazioni richieste
*** Operazione 1
*** Operazione 2
** Modello ER
** Regole di Gestione
*** Vincoli d'integrità
*** Regole di derivazione
** Progettazione Logica
*** Tabella volumi
*** Analisti ridondanze
*** Costi operazione
**** Presenza di ridondanza
**** Assenza di ridondanza
*** Eliminazione delle generalizzazioni
*** Selezione degli identificatori primari
*** Traduzione modello logico
** Progettazione Fisica
*** Definizione database in SQL
**** Definizione dati
***** Creazione tabelle
***** Definizione trigger
**** Popolazione database
**** Query
** Analisi con R
** Conclusioni
